---
layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "29"
year: "2016"
contributor: 
- "Ben Kaden"
title: "Hinweis auf ein Buch. Christoph Tempel: Zweckfigur wird Ornament. Bauten und Projekte [von] Rolf Ramcke. Berlin: jovis, 2016"
urn: "urn:nbn:de:kobv:11-100238225"
date: 2016-06-14 13:00
comments: false
sharing: true
footer: true
---
