---
layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "29"
year: "2016"
contributor: 
- "Karsten Schuldt"
title: "Textarbeit und nervöses Pochen darauf, dass sich alles ändern wird.
Muss. Rezension zu: Stefan Alker ; Achim Hölter (Hrsg.). Literaturwissenschaft
und Bibliotheken. (Bibliothek im Kontext; 2) Wien: Vienna University Press, 2015. 30.00 €. (Auch als Open Access http://doi.org/10.14220/9783737004541)"
urn: "urn:nbn:de:kobv:11-100238216"
date: 2016-06-14 13:00
comments: false
sharing: true
footer: true
---
