---
layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "29"
year: "2016"
contributor: 
- "Timotheus Chang-whae Kim"
- "Philipp Zumstein"
title: "Zurück ins Web. Die Entwicklung eines neuen Webauftritts für die Nordrhein-Westfälische Bibliographie (NWBib)"
date: 2016-06-16 13:00
abstract: "<b>Zusammenfassung</b>: Im Folgenden soll aufgezeigt werden, wie derzeit
das Literaturverwaltungsprogramm Zotero innerhalb des Index Theologicus
genutzt wird, um unselbstständige Literatur in einem bibliothekarischen
Katalogisierungssystem zu erfassen. Die modulare und flexible
Architektur der Open Source Software erlaubt es, die bereits
kollaborativ zusammengetragene Programmierarbeit zur Datenextraktion
mitzunutzen. Das vorgestellte semiautomatische Verfahren bringt auch bei
der Verknüpfung von Normdaten erhebliche Vorteile für die
Medienbearbeitung.
</br>
<b>Schlüsselwörter</b>: Literauturverwaltungsprogramm, Zotero,
Katalogisierung, Unselbständige Werke, Aufsatzliteratur, Index
Theologicus, Online-Bibliographie, WinIBW, Fachinformationsdienst
Theologie
</br>
<b>Abstract:</b> This article presents an approach to use the reference
management software Zotero within the theological article database Index
Theologicus to catalogue article metadata for a library management
system. Zotero's Open Source nature and flexible architecture allowed us
to seamlessly reuse the vast amount of data extraction routines
collaboratively developed for the software. We will show how the
semi-automatic workflow we developed will make authority linking fun
again.
</br>
<b>Keywords:</b> Reference Management System, Zotero, Cataloguing, Journal
articles, Index Theologicus, Theological database, Academic Information
Services for Theology"
urn: "urn:nbn:de:kobv:11-100238157"
comments: false
sharing: true
footer: true
---
