---
layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "29"
year: "2016"
contributor: 
- "Jakob Voß"
title: "Versuch einer Bibliographie von Bibliographien von Bibliographien von Bibliographien"
abstract: "Der Artikel beschreibt die Erstellung einer Meta-Meta-Meta-Bibliographie und liefert eine Bewertung des Ergebnis, bestehend aus vier Universalbibliographien und vier Auswahlbibliographien."
urn: "urn:nbn:de:kobv:11-100238115"
date: 2016-06-06 13:00
comments: false
sharing: true
footer: true
...
