---
layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "29"
year: "2016"
contributor: 
- "Redaktion LIBREAS"
title: "Editorial #29: Bibliographien"
urn: "urn:nbn:de:kobv:11-100238106"
date: 2016-06-14 13:00
comments: false
sharing: true
footer: true
---
