---
layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "29"
year: "2016"
contributor: 
- "Marius Hug"
- "Benjamin Fiechter"
- "Christian Thomas"
title: "Texte über fallende Steine. Alexander von Humboldts Praktiken wissenschaftlichen Arbeitens am Beispiel der <q>Mondvulkane</q>"
date: 2016-06-16 13:00
urn: "urn:nbn:de:kobv:11-100238186"
comments: false
sharing: true
footer: true
---
